import {
	BugIcon,
	DarkIcon,
	DragonIcon,
	ElectricIcon,
	FairyIcon,
	FightingIcon,
	FireIcon,
	FlyingIcon,
	GhostIcon,
	GrassIcon,
	GroundIcon,
	IceIcon,
	NormalIcon,
	PoisonIcon,
	PsychicIcon,
	RockIcon,
	SteelIcon,
	WaterIcon,
} from "@components/Icons";

export const types = [
	{ name: "Bug", icon: BugIcon },
	{ name: "Dark", icon: DarkIcon },
	{ name: "Dragon", icon: DragonIcon },
	{ name: "Electric", icon: ElectricIcon },
	{ name: "Fairy", icon: FairyIcon },
	{ name: "Fighting", icon: FightingIcon },
	{ name: "Fire", icon: FireIcon },
	{ name: "Flying", icon: FlyingIcon },
	{ name: "Ghost", icon: GhostIcon },
	{ name: "Grass", icon: GrassIcon },
	{ name: "Ground", icon: GroundIcon },
	{ name: "Ice", icon: IceIcon },
	{ name: "Normal", icon: NormalIcon },
	{ name: "Poison", icon: PoisonIcon },
	{ name: "Psychic", icon: PsychicIcon },
	{ name: "Rock", icon: RockIcon },
	{ name: "Steel", icon: SteelIcon },
	{ name: "Water", icon: WaterIcon },
];
